// Simulator configuration and visualization. Acquisition remains in the Python backend.
let neuronPositions=[], simulatorSelection=0, simulatorDrag=false, simulatorGrid=null, simulatorTargets=new Set();
const simPanel=document.createElement('section');simPanel.className='panel';
simPanel.innerHTML=`<div class="sim-layout"><div><h2>Build your culture</h2>
<p class="help">Electrodes sample nearby neurons. Select a neuron to see its Gaussian waveform footprint; drag it to move it. In Place mode, click empty space to add a neuron. To wire a neuron to several others, select it, then switch to Connect mode and click each target.</p>
<div class="fields">
<div><label for="simNeurons">Neurons</label><input id="simNeurons" type="number" min="1" max="256" value="40"></div>
<div><label for="simPitch">Electrode spacing (µm)</label><input id="simPitch" type="number" min="1" step=".5" value="17.5"></div>
<div><label for="simSigma">Spatial spread σ (µm)</label><input id="simSigma" type="number" min="1" step="1" value="20"></div>
<div><label for="simAmplitude">Waveform amplitude (µV)</label><input id="simAmplitude" type="number" min="1" step="5" value="85"></div></div>
<div class="toolbar"><button id="simGrid">20 × 20 electrodes</button><button id="simScatter">Scatter neurons</button></div>
<label for="simMode">Canvas tool</label><select id="simMode"><option value="move">Select / move neurons</option><option value="place">Place neurons</option><option value="connect">Connect from selected neuron</option></select>
<div class="sim-edit" style="margin-top:12px"><div><label for="simSelected">Selected neuron</label><select id="simSelected"></select></div><div><label for="simX">x (µm)</label><input id="simX" type="number" step=".5"></div><div><label for="simY">y (µm)</label><input id="simY" type="number" step=".5"></div></div>
<div class="toolbar"><button id="simDelete">Remove neuron</button></div>
<h2>Connect neurons</h2><div class="sim-edit"><div><label for="simFrom">Source neuron</label><select id="simFrom"></select></div><div><label for="simTo">Target neuron</label><select id="simTo"></select></div><div><label for="simEdge">Weight</label><input id="simEdge" type="number" min="-2" max="2" step=".05" value=".35"></div></div>
<div class="toolbar"><button id="simConnect">Set connection</button><button id="simDisconnect">Remove connection</button></div>
<p id="simConnectHelp" class="help">Select a source above, then choose targets below. In Connect mode, click neurons to set connections immediately; Shift-click removes them. The source stays selected.</p><div id="simTargets" role="group" aria-label="Connection targets" style="display:flex;flex-wrap:wrap;gap:4px;max-height:160px;overflow:auto"></div><div class="toolbar"><button id="simTargetsAll">Select all other neurons</button><button id="simTargetsNone">Clear selection</button><button id="simConnectMany">Set selected connections</button><button id="simDisconnectMany">Remove selected connections</button></div><p id="simTargetStatus" role="status" class="help"></p><p class="help">Blue arrows excite; orange arrows inhibit. Only connections touching the selected neuron are drawn. The full matrix below supports painting multiple connections.</p>
</div><div><h2>Neurons and electrode footprint</h2><canvas id="simCulture" aria-label="Neuron positions and electrode footprint; use the selected neuron and coordinate inputs for keyboard editing"></canvas><p id="simGeometry" class="help sim-readout"></p><p class="help">Squares: recording electrodes · Circles: neurons · Shading: expected negative peak from the selected neuron. Electrode IDs use Maxwell row × 220 + column; channel indices are contiguous. This is a model preview, not a recording.</p><p id="simMessage" role="status" class="help sim-status"></p></div></div>
<p class="help">Source: BrainDance's NumPy spiking network (leaky integrate-and-fire neurons). Spikes inject biphasic extracellular waveforms onto nearby electrodes with Gaussian amplitude decay. The same raw acquisition stream feeds recording phases and spike detection.</p>`;
views.simulation.insertBefore(simPanel,$('connectivityPanel'));
const recordingPanel=document.createElement('section');recordingPanel.className='panel';
recordingPanel.innerHTML=`<h2>Try a simulated recording</h2><p class="help">Test your experiment’s simulated data source here. Record the culture and watch the electrode map, raw voltage and detected spikes in Live recording.</p><div class="fields"><div><label for="simSeconds">Recording duration (seconds)</label><input id="simSeconds" type="number" min=".02" step="1" value="20"></div><div><label for="simDetection">Spike detection</label><select id="simDetection"></select></div><div><label for="simThreshold">Threshold magnitude (µV)</label><input id="simThreshold" type="number" min="1" value="45"></div><div><label for="simSorter">RT-sort saved sorter path</label><input id="simSorter" placeholder="Required only for RT-sort"></div></div><div class="toolbar"><button id="simRecord" class="primary">Start recording</button><label><input id="simSave" type="checkbox" style="width:auto" checked> Save raw recording</label><span id="simUnavailable" class="help"></span></div>`;
views.simulation.insertBefore(recordingPanel,simPanel);
$('simDetection').replaceChildren(...Array.from($('detection').options||[],option=>new Option(option.text,option.value)));
$('simDetection').value=$('detection').value;
$('simDetection').onchange=()=>{$('detection').value=$('simDetection').value;$('detection').dispatchEvent(new Event('change',{bubbles:true}));};
$('detection').addEventListener('change',()=>{$('simDetection').value=$('detection').value;});
const spatialPanel=document.createElement('section');spatialPanel.className='panel wide';
spatialPanel.innerHTML=`<div class="row"><h2>Live electrode activity</h2><div><label for="spatialMetric">Signal</label><select id="spatialMetric"><option value="peak_uv">Negative peak (µV)</option><option value="rms_uv">RMS voltage (µV)</option></select></div></div><canvas id="spatialLive" aria-label="Live raw voltage amplitude on the electrode array"></canvas><p id="spatialHover" class="help" aria-live="polite">Hover over an electrode to inspect its channel and physical electrode ID.</p><p id="spatialLegend" class="help">Start a recording to see spatial voltage activity.</p>`;
monitorGrid.insertBefore(spatialPanel,$('raw').parentElement);
function simulatorExtent(){const n=Number($('channels').value),cols=simulatorGrid?.[1]||Math.min(4,n),rows=simulatorGrid?.[0]||Math.ceil(n/cols),pitch=Number($('simPitch').value)||17.5;return {n,cols,rows,pitch,x:Math.max(1,cols-1)*pitch,y:Math.max(1,rows-1)*pitch};}
function simulatorElectrodes(){const g=simulatorExtent();return Array.from({length:g.n},(_,i)=>[i%g.cols*g.pitch,Math.floor(i/g.cols)*g.pitch]);}
function simulatorConfig(){return {num_neurons:neuronPositions.length,neuron_positions:neuronPositions.map(p=>p.slice()),grid_shape:simulatorGrid,electrode_pitch_um:Number($('simPitch').value),spatial_sigma_um:Number($('simSigma').value),waveform_amplitude_uv:Number($('simAmplitude').value),threshold_uv:-Math.abs(Number($('simThreshold').value)),sorter_path:$('simSorter').value||null,write_output:$('simSave').checked};}
function loadSimulator(values){simulatorGrid=values.grid_shape||null;$('simNeurons').value=values.num_neurons||values.adjacency?.length||values.channels||40;$('simPitch').value=values.electrode_pitch_um||17.5;$('simSigma').value=values.spatial_sigma_um||20;$('simAmplitude').value=values.waveform_amplitude_uv||85;$('simThreshold').value=Math.abs(values.threshold_uv||45);$('simSorter').value=values.sorter_path||'';$('simSave').checked=values.write_output!==false;neuronPositions=(values.neuron_positions||(Number($('simNeurons').value)===Number($('channels').value)?simulatorElectrodes():[])).map(p=>p.slice());resizeNeurons(Number($('simNeurons').value),false);}
function simulatorUnavailable(){return $('dataSource')?.value ? $('dataSource').value!=='simulation' : !!(settings.source||settings.live_config);}
function simChanged(){matrixDirty=true;if(typeof scheduleValidation==='function')scheduleValidation();$('simMessage').textContent='Setup ready for the next recording. Save a profile to keep it.';}
function resizeNeurons(n,changed=true){if(!Number.isInteger(n)||n<1||n>256){error('Choose 1–256 neurons.');return;}const g=simulatorExtent();while(neuronPositions.length<n){const i=neuronPositions.length;neuronPositions.push([((i*.61803398875+.17)%1)*g.x,((i*.41421356237+.31)%1)*g.y]);}neuronPositions.length=n;matrixValues=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>matrixValues[i]?.[j]??0));simulatorSelection=Math.min(simulatorSelection,n-1);$('simNeurons').value=n;renderMatrix();simulatorSelectOptions();if(changed)simChanged();}
function simulatorSelectOptions(){for(const id of ['simSelected','simFrom','simTo']){const old=$(id).value;$(id).replaceChildren(...neuronPositions.map((_,i)=>new Option(`Neuron ${i}`,i)));$(id).value=Math.min(Number(old)||0,neuronPositions.length-1);}$('simSelected').value=simulatorSelection;$('simFrom').value=simulatorSelection;simulatorTargets=new Set([...simulatorTargets].filter(i=>i<neuronPositions.length&&i!==simulatorSelection));simulatorCoordinates();renderSimulatorTargets();}
function simulatorCoordinates(){const p=neuronPositions[simulatorSelection];if(!p)return;$('simX').value=p[0].toFixed(1);$('simY').value=p[1].toFixed(1);}
function resizeSimulatorGrid(n){simulatorGrid=n===400?[20,20]:null;simChanged();}
$('simNeurons').onchange=()=>resizeNeurons(Number($('simNeurons').value));
$('simGrid').onclick=()=>{$('channels').value=400;simulatorGrid=[20,20];simChanged();};
$('simScatter').onclick=()=>{neuronPositions=[];resizeNeurons(Number($('simNeurons').value));};
for(const id of ['simPitch','simSigma','simAmplitude'])$(id).onchange=simChanged;
$('simSelected').onchange=()=>selectSimulatorNeuron(Number($('simSelected').value));
$('simFrom').onchange=()=>selectSimulatorNeuron(Number($('simFrom').value));
for(const id of ['simX','simY'])$(id).onchange=()=>{const g=simulatorExtent(),x=Number($('simX').value),y=Number($('simY').value);if(!Number.isFinite(x+y)||x<0||y<0||x>g.x||y>g.y){error('Place neurons within the electrode workspace.');simulatorCoordinates();return;}neuronPositions[simulatorSelection]=[x,y];simChanged();};
$('simDelete').onclick=()=>{if(neuronPositions.length<=1)return;simulatorTargets.clear();neuronPositions.splice(simulatorSelection,1);matrixValues.splice(simulatorSelection,1);matrixValues.forEach(row=>row.splice(simulatorSelection,1));resizeNeurons(neuronPositions.length);};
function selectSimulatorNeuron(index){simulatorSelection=index;simulatorTargets.clear();simulatorSelectOptions();}
function renderSimulatorTargets(){
 $('simTargets').replaceChildren(...neuronPositions.map((_,i)=>{const button=document.createElement('button');button.type='button';button.textContent=`N${i}`;button.disabled=i===simulatorSelection&&!$('selfConnections').checked;button.setAttribute('aria-label',`Target neuron ${i}`);button.setAttribute('aria-pressed',String(simulatorTargets.has(i)));button.style.background=simulatorTargets.has(i)?'var(--accent)':'';button.style.color=simulatorTargets.has(i)?'#fff':'';button.onclick=()=>{if(simulatorTargets.has(i))simulatorTargets.delete(i);else simulatorTargets.add(i);renderSimulatorTargets();};return button;}));
 $('simTargetStatus').textContent=`Source N${simulatorSelection} · ${simulatorTargets.size} targets selected`;
}
function setSimulatorConnections(targets,remove=false){
 if(simulatorUnavailable())return error('Connections are available for simulated data only.');
 const from=simulatorSelection,weight=remove?0:Number($('simEdge').value);
 if(!Number.isFinite(weight)||Math.abs(weight)>2)return error('Weight must be between -2 and 2.');
 if(!targets.length)return error('Select at least one target neuron.');
 if(targets.includes(from)&&!$('selfConnections').checked)return error('Enable self-connections in the matrix to connect a neuron to itself.');
 for(const to of targets)matrixValues[to][from]=weight;
 matrixDirty=true;renderMatrix();applyMatrix();
 $('simMessage').textContent=`${remove?'Removed':'Set'} ${targets.length} connection${targets.length===1?'':'s'} from N${from}${remove?'':` at weight ${weight.toFixed(2)}`}.`;
}
for(const [id,remove] of [['simConnect',false],['simDisconnect',true]])$(id).onclick=()=>setSimulatorConnections([Number($('simTo').value)],remove);
for(const [id,remove] of [['simConnectMany',false],['simDisconnectMany',true]])$(id).onclick=()=>setSimulatorConnections([...simulatorTargets],remove);
$('simTargetsAll').onclick=()=>{simulatorTargets=new Set(neuronPositions.map((_,i)=>i).filter(i=>i!==simulatorSelection));renderSimulatorTargets();};
$('simTargetsNone').onclick=()=>{simulatorTargets.clear();renderSimulatorTargets();};
$('selfConnections').addEventListener('change',()=>{if(!$('selfConnections').checked)simulatorTargets.delete(simulatorSelection);renderSimulatorTargets();});
function simProjection(w,h,positions){const xs=positions.map(p=>p[0]),ys=positions.map(p=>p[1]),xmin=Math.min(0,...xs),ymin=Math.min(0,...ys),xmax=Math.max(1,...xs),ymax=Math.max(1,...ys),scale=Math.min((w-40)/(xmax-xmin),(h-40)/(ymax-ymin));return {scale,x0:(w-(xmax-xmin)*scale)/2,y0:(h-(ymax-ymin)*scale)/2,xmin,ymin,point:p=>[(p[0]-xmin)*scale+(w-(xmax-xmin)*scale)/2,(p[1]-ymin)*scale+(h-(ymax-ymin)*scale)/2]};}
function simPointer(event){const rect=$('simCulture').getBoundingClientRect(),projection=simProjection(rect.width,rect.height,simulatorElectrodes()),g=simulatorExtent();return [Math.max(0,Math.min(g.x,(event.clientX-rect.left-projection.x0)/projection.scale+projection.xmin)),Math.max(0,Math.min(g.y,(event.clientY-rect.top-projection.y0)/projection.scale+projection.ymin))];}
$('simCulture').onpointerdown=event=>{if(simulatorUnavailable())return;const connect=$('simMode').value==='connect';if(running()&&!connect)return;const p=simPointer(event),g=simulatorExtent();let nearest=-1,distance=g.pitch*.65;neuronPositions.forEach((q,i)=>{const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<distance){nearest=i;distance=d;}});if(nearest<0&&$('simMode').value==='place'&&neuronPositions.length<256){neuronPositions.push(p);resizeNeurons(neuronPositions.length);nearest=neuronPositions.length-1;}if(nearest<0)return;
 if(connect){$('simTo').value=nearest;setSimulatorConnections([nearest],event.shiftKey);return;}
 selectSimulatorNeuron(nearest);simulatorDrag=true;$('simCulture').setPointerCapture(event.pointerId);};
$('simCulture').onpointermove=event=>{if(!simulatorDrag)return;neuronPositions[simulatorSelection]=simPointer(event);simulatorCoordinates();};
for(const name of ['pointerup','pointercancel'])$('simCulture').addEventListener(name,()=>{if(simulatorDrag){simulatorDrag=false;simChanged();}});
$('simRecord').onclick=async()=>{if(running())return error('Stop the current run before starting a recording.');try{const seconds=Number($('simSeconds').value);if(!Number.isFinite(seconds)||seconds<.02)throw Error('Enter a positive recording duration.');const config=collect();config.phases=[{id:'recording',type:'recording',params:{record_seconds:seconds}}];if(await control('start',{config,profile:selectedProfile,skip:false}))showView('monitor');}catch(e){error(e.message);}};
function drawSimulator(){const unavailable=simulatorUnavailable(),locked=running()||unavailable;for(const id of ['simNeurons','simPitch','simSigma','simAmplitude','simGrid','simScatter','simX','simY','simDelete','channels','seed'])$(id).disabled=locked;$('simMode').disabled=unavailable;for(const id of ['simFrom','simTo','simEdge','simConnect','simDisconnect','simConnectMany','simDisconnectMany','simTargetsAll','simTargetsNone'])$(id).disabled=unavailable;$('simDetection').disabled=locked;$('simDetection').value=$('detection').value;$('simRecord').disabled=locked;$('simUnavailable').textContent=unavailable?'Simulator disabled for recorded-file or hardware sources.':'';
 if(!views.simulation.hidden){const[c,w,h]=canvas('simCulture'),electrodes=simulatorElectrodes(),p=simProjection(w,h,electrodes),selected=neuronPositions[simulatorSelection],sigma=Number($('simSigma').value)||20,pitch=simulatorExtent().pitch;
 for(const xy of electrodes){const a=selected?Math.exp(-((xy[0]-selected[0])**2+(xy[1]-selected[1])**2)/(2*sigma*sigma)):0,q=p.point(xy),size=Math.max(2,Math.min(14,pitch*p.scale*.65));c.fillStyle=`rgba(43,101,163,${.1+.8*a})`;c.fillRect(q[0]-size/2,q[1]-size/2,size,size);}
 matrixValues.forEach((row,to)=>row.forEach((weight,from)=>{if(!weight||(from!==simulatorSelection&&to!==simulatorSelection)||!neuronPositions[from]||!neuronPositions[to])return;const a=p.point(neuronPositions[from]),b=p.point(neuronPositions[to]),angle=Math.atan2(b[1]-a[1],b[0]-a[0]);c.strokeStyle=c.fillStyle=weight>0?'#2b65a3':'#b45c28';c.lineWidth=1+Math.abs(weight);c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();const tip=[b[0]-8*Math.cos(angle),b[1]-8*Math.sin(angle)];c.beginPath();c.moveTo(...tip);c.lineTo(tip[0]-7*Math.cos(angle-.5),tip[1]-7*Math.sin(angle-.5));c.lineTo(tip[0]-7*Math.cos(angle+.5),tip[1]-7*Math.sin(angle+.5));c.fill();}));
 neuronPositions.forEach((xy,i)=>{const q=p.point(xy);c.fillStyle=i===simulatorSelection?'#e6a23a':'#fff';c.strokeStyle='#314d6b';c.lineWidth=2;c.beginPath();c.arc(...q,i===simulatorSelection?7:5,0,Math.PI*2);c.fill();c.stroke();if(i===simulatorSelection){c.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink');c.font='12px system-ui';c.fillText(`N${i}`,q[0]+10,q[1]-9);}});const g=simulatorExtent();$('simGeometry').textContent=`${g.rows} × ${g.cols} grid · ${g.n} channels · ${neuronPositions.length} neurons · ${g.x.toFixed(1)} × ${g.y.toFixed(1)} µm`;
 }
 if(!views.monitor.hidden){const spatial=state.spatial,[c,w,h]=canvas('spatialLive');if(!spatial?.channel_positions?.length){$('spatialLegend').textContent='Start a recording to see spatial voltage activity.';return;}const metric=$('spatialMetric').value,values=spatial[metric]||[],positions=spatial.channel_positions,p=simProjection(w,h,positions),maximum=Math.max(1,...values),gaps=positions.slice(1).map((q,i)=>Math.hypot(q[0]-positions[i][0],q[1]-positions[i][1])).filter(v=>v>0),size=Math.max(2,Math.min(22,(gaps.length?Math.min(...gaps):17.5)*p.scale*.8));positions.forEach((xy,i)=>{const q=p.point(xy),v=Math.max(0,values[i]||0)/maximum;c.fillStyle=`rgb(${Math.round(235-205*v)},${Math.round(241-133*v)},${Math.round(249-81*v)})`;c.fillRect(q[0]-size/2,q[1]-size/2,size,size);});$('spatialLegend').textContent=`${state.status==='running'&&!state.paused?'Live':'Last acquired bin'} · ${positions.length} electrodes · ${metric==='rms_uv'?'RMS voltage':'Negative peak'} · scale 0–${maximum.toFixed(1)} µV · latest 20 ms of acquired raw voltage`;}
}
loadSimulator(settings.num_neurons?settings:{...settings,num_neurons:40,grid_shape:[20,20]});

$('spatialLive').onpointermove=event=>{const spatial=state.spatial;if(!spatial?.channel_positions?.length)return;const rect=$('spatialLive').getBoundingClientRect(),p=simProjection(rect.width,rect.height,spatial.channel_positions),x=event.clientX-rect.left,y=event.clientY-rect.top;let nearest=-1,distance=20;spatial.channel_positions.forEach((xy,i)=>{const q=p.point(xy),d=Math.hypot(q[0]-x,q[1]-y);if(d<distance){nearest=i;distance=d;}});if(nearest<0)return;const xy=spatial.channel_positions[nearest],electrode=spatial.electrodes?.[nearest];$('spatialHover').textContent=`Channel ${nearest}${electrode===undefined?'':` · electrode ${electrode}`} · (${xy[0].toFixed(1)}, ${xy[1].toFixed(1)}) µm · ${(spatial[$('spatialMetric').value]?.[nearest]||0).toFixed(1)} µV`;};
